---
- name: Check if running on Debian 9, 10, or 11
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_version == "11" or ansible_distribution_version == "10" or ansible_distribution_version == "9"
  tags: unifi

- name: Install unifi dependencies
  apt:
    name:
      - gpg
      - ca-certificates
      - apt-transport-https
  become: true
  tags: unifi

- import_tasks: "pre.yml"
  tags: unifi
  when: ansible_distribution_version == "11" or ansible_distribution_version == "10"

- meta: flush_handlers

- name: Add unifi repo key
  apt_key:
    url: https://dl.ui.com/unifi/unifi-repo.gpg
    state: present
  become: true
  tags: unifi

- name: Add unifi repo
  apt_repository:
    filename: 100-unifi
    repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
    state: present
  become: true
  tags: unifi

- name: Install unifi package
  apt:
    name: unifi
    state: present
  become: true
  tags: unifi

- name: Put unifi package on hold
  dpkg_selections:
    name: unifi
    selection: hold
  become: true
  tags: unifi

- import_tasks: "post.yml"
  tags: unifi
  when: ansible_distribution_version == "11" or ansible_distribution_version == "10"

- meta: flush_handlers

- name: Start and enable unifi
  systemd:
    name: unifi
    state: started
    enabled: true
  become: true
  tags: unifi
