---
- name: Check if running on Debian 9, 10, or 11
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_version == "11" or ansible_distribution_version == "10" or ansible_distribution_version == "9"
  tags: 
    - unifi
    - always

- name: Install unifi dependencies
  apt:
    name:
      - gpg
      - ca-certificates
      - apt-transport-https
  become: true
  tags: unifi

- import_tasks: repos.yml
  tags: unifi
  when: ansible_distribution_version == "11" or ansible_distribution_version == "10"

- name: Add unifi repo key
  apt_key:
    url: https://dl.ui.com/unifi/unifi-repo.gpg
    state: present
  become: true
  tags: unifi

- name: Add unifi repo
  apt_repository:
    filename: 100-unifi
    repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
    state: present
  become: true
  tags: unifi

- name: Install unifi package
  apt:
    name: unifi
    state: present
  become: true
  tags: unifi

- name: Update unifi
  apt:
    name: unifi
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: "'unifi_update' in ansible_run_tags"
  tags: 
    - unifi
    - unifi_update

- name: Put unifi package on hold or install
  dpkg_selections:
    name: unifi
    selection: "{{ (unifi_hold | bool) | ternary('hold', 'install') }}"
  become: true
  tags: 
    - unifi
    - unifi_update

- name: Start and enable unifi
  systemd:
    name: unifi
    state: started
    enabled: true
  become: true
  tags: unifi
