# vim:ft=yaml.ansible
---
- name: Install unifi dependencies
  ansible.builtin.apt:
    name:
      - gpg
      - ca-certificates
      - apt-transport-https
  become: true
  tags: unifi

- name: Import mongodb.yml
  ansible.builtin.import_tasks: mongodb.yml
  tags: unifi

- name: Add unifi repo key
  ansible.builtin.apt_key:
    url: https://dl.ui.com/unifi/unifi-repo.gpg
    state: present
  become: true
  tags: unifi

- name: Add unifi repo
  ansible.builtin.apt_repository:
    filename: 100-unifi
    repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
    state: present
  become: true
  tags: unifi

- name: Install unifi package
  ansible.builtin.apt:
    name: unifi
    state: present
  become: true
  tags: unifi

- name: Put unifi package on hold or install
  ansible.builtin.dpkg_selections:
    name: unifi
    selection: "{{ (unifi_hold | bool) | ternary('hold', 'install') }}"
  become: true
  tags: unifi

- name: Start and enable unifi
  ansible.builtin.systemd:
    name: unifi
    state: started
    enabled: true
  become: true
  tags: unifi
