---
- name: Add mongodb 3.6 repo key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.6.asc
    state: present
  become: true
  tags: unifi

- name: Add mongodb 3.6 repo
  apt_repository:
    filename: 100-mongodb
    repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main
    state: present
  become: true
  tags: unifi
