# vim:ft=yaml.ansible
---
- name: Install libssl1
  ansible.builtin.apt:
    deb: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
    state: present
  become: true
  tags: unifi

- name: Add mongodb 4.4 repo key
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | gpg -o /usr/share/keyrings/mongodb-server-4.4.gpg --dearmor
    creates: /usr/share/keyrings/mongodb-server-4.4.gpg
  args:
    executable: /bin/bash
  become: true
  tags: unifi

- name: Add mongodb 4.4 repo
  ansible.builtin.apt_repository:
    filename: mongodb-org-4.4
    repo: "deb [ signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg ] http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main"
    state: present
  become: true
  tags: unifi
