# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  galaxy:
    name: Publish to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: pip3 install ansible

      - name: Publish to Ansible Galaxy
        run: ansible-galaxy role import ${{ github.repository_owner }} $(basename ${{ github.repository }}) --token $ANSIBLE_GALAXY_TOKEN
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
